feat(hooks): (Issue #2) modificar hook pre-commit para que valide la rama de trabajo

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,12 +1,19 @@
 #!/bin/bash
 
-# Hook pre-commit: se previene commits si hay cambios que aún no están en "staged" (archivos sin agregar).
-# Se planea luego agregar linters
+# Obteniendo la rama actual
+branch=$(git symbolic-ref --short HEAD)
 
-if ! git diff --quiet; then
-  echo "Pre-commit: Hay archivos en 'staged' que fueron modificados. Por favor, vuelva a agregarlos."
-  exit 1
-fi
+# Ramas protegidas donde no se permite hacer commits
+ramas_protegidas=("main" "develop" "release")
 
-# Si todos están en sección 'staged', entonces se acepta el commit.
+# Verificar si la rama actual está en la lista de ramas protegidas
+for rama in "${ramas_protegidas[@]}"; do
+  if [[ "$branch" == "$rama" ]]; then
+    echo "ERROR: No está permitido hacer commit directamente en la rama '$branch'."
+    echo "Por favor, cree una rama de trabajo para hacer tus commits."
+    exit 1
+  fi
+done
+
+# Si pasa
 exit 0
